"""
ARC Rule Hypothesizer — analyzes training pairs and generates C programs.

The hypothesizer looks at input→output training pairs and attempts to
infer the transformation rule. It generates candidate C programs that
implement the rule for compilation via transformer-vm.

Strategy hierarchy:
1. Exact pattern matching (color map, identity, constant output)
2. Geometric transforms (rotate, flip, transpose, scale)
3. Grid operations (tile, crop, fill, overlay)
4. Compositional (combine multiple simple transforms)

Each hypothesis is a C program string ready for compilation.
"""

import json
import logging
from collections import Counter
from typing import List, Optional, Tuple

from .grid_io import Grid, grids_equal

logger = logging.getLogger(__name__)

# Path to the arc_grid.h header (relative to wasm_tools/)
ARC_HEADER = "arc/arc_grid.h"

# ── C code templates ─────────────────────────────────────────────

C_PREAMBLE = '''/* ARC rule: {description}
 * Auto-generated by self-compiling intelligence loop.
 */
#include "{header_path}"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {{
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;
'''

C_EPILOGUE = '''
    arc_emit_grid(out, oh, ow);
}
'''


def _make_c_program(body: str, description: str, header_path: str = ARC_HEADER) -> str:
    """Wrap a C body in the standard ARC program template."""
    return C_PREAMBLE.format(description=description, header_path=header_path) + body + C_EPILOGUE


# ── Analysis helpers ─────────────────────────────────────────────

def _dimensions(grid: Grid) -> Tuple[int, int]:
    return (len(grid), len(grid[0]) if grid else 0)


def _flatten(grid: Grid) -> List[int]:
    return [v for row in grid for v in row]


def _color_histogram(grid: Grid) -> Counter:
    return Counter(_flatten(grid))


def _rotate_90(grid: Grid) -> Grid:
    """Rotate grid 90 degrees clockwise."""
    h, w = len(grid), len(grid[0])
    return [[grid[h - 1 - r][c] for r in range(h)] for c in range(w)]


def _rotate_180(grid: Grid) -> Grid:
    return _rotate_90(_rotate_90(grid))


def _rotate_270(grid: Grid) -> Grid:
    return _rotate_90(_rotate_90(_rotate_90(grid)))


def _flip_h(grid: Grid) -> Grid:
    """Flip horizontally (left-right)."""
    return [row[::-1] for row in grid]


def _flip_v(grid: Grid) -> Grid:
    """Flip vertically (top-bottom)."""
    return grid[::-1]


def _transpose(grid: Grid) -> Grid:
    h, w = len(grid), len(grid[0])
    return [[grid[r][c] for r in range(h)] for c in range(w)]


# ── Hypothesis generators ────────────────────────────────────────

class Hypothesis:
    """A candidate transformation rule with its C implementation."""

    def __init__(self, name: str, description: str, c_code: str, confidence: float = 0.5):
        self.name = name
        self.description = description
        self.c_code = c_code
        self.confidence = confidence

    def __repr__(self):
        return f"Hypothesis({self.name!r}, conf={self.confidence:.2f})"


def _try_color_map(pairs: List[dict]) -> Optional[Hypothesis]:
    """Check if the rule is a per-cell color mapping (each color maps to another)."""
    # Collect all color mappings across all pairs
    mapping = {}
    for pair in pairs:
        inp, out = pair["input"], pair["output"]
        h_i, w_i = _dimensions(inp)
        h_o, w_o = _dimensions(out)
        if h_i != h_o or w_i != w_o:
            return None  # Dimensions change → not a simple color map
        for r in range(h_i):
            for c in range(w_i):
                src, dst = inp[r][c], out[r][c]
                if src in mapping:
                    if mapping[src] != dst:
                        return None  # Inconsistent mapping
                else:
                    mapping[src] = dst

    if not mapping:
        return None

    # Check it's not identity
    if all(k == v for k, v in mapping.items()):
        return None

    # Generate C code with a lookup table
    # Build the map array (0-9 → mapped value, default to identity)
    lut = list(range(10))
    for src, dst in mapping.items():
        lut[src] = dst

    desc = "color map: " + ", ".join(f"{k}->{v}" for k, v in sorted(mapping.items()))
    body = f"""
    /* Color mapping lookup table */
    int lut[10];
    lut[0]={lut[0]}; lut[1]={lut[1]}; lut[2]={lut[2]}; lut[3]={lut[3]}; lut[4]={lut[4]};
    lut[5]={lut[5]}; lut[6]={lut[6]}; lut[7]={lut[7]}; lut[8]={lut[8]}; lut[9]={lut[9]};
    oh = h; ow = w;
    int total = 0;
    int i;
    for (i = 0; i < h; i++) total = total + w;
    for (i = 0; i < total; i++) {{
        out[i] = lut[grid[i]];
    }}"""

    return Hypothesis("color_map", desc, _make_c_program(body, desc), confidence=0.95)


def _try_identity(pairs: List[dict]) -> Optional[Hypothesis]:
    """Check if output == input."""
    for pair in pairs:
        if not grids_equal(pair["input"], pair["output"]):
            return None

    body = """
    oh = h; ow = w;
    arc_copy(out, grid, h, w);"""

    return Hypothesis("identity", "output equals input", _make_c_program(body, "identity"), confidence=0.99)


def _try_constant_output(pairs: List[dict]) -> Optional[Hypothesis]:
    """Check if all outputs are the same grid regardless of input."""
    if len(pairs) < 2:
        return None
    first_out = pairs[0]["output"]
    for pair in pairs[1:]:
        if not grids_equal(pair["output"], first_out):
            return None

    # Constant output — encode it directly
    h, w = _dimensions(first_out)
    flat = _flatten(first_out)
    vals = ", ".join(str(v) for v in flat)
    total = h * w

    body = f"""
    oh = {h}; ow = {w};
    int vals[{total}] = {{{vals}}};
    int i;
    for (i = 0; i < {total}; i++) out[i] = vals[i];"""

    return Hypothesis("constant_output", f"constant {h}x{w} output",
                       _make_c_program(body, "constant output"), confidence=0.9)


def _try_geometric_transform(pairs: List[dict]) -> Optional[Hypothesis]:
    """Check for rotate 90/180/270, flip H/V, transpose."""
    transforms = [
        ("rotate_90", _rotate_90, """
    oh = w; ow = h;
    int r, c;
    for (c = 0; c < w; c++) {
        for (r = 0; r < h; r++) {
            arc_set(out, oh, c, h - 1 - r, arc_get(grid, w, r, c));
        }
    }"""),
        ("rotate_180", _rotate_180, """
    oh = h; ow = w;
    int r, c;
    for (r = 0; r < h; r++) {
        for (c = 0; c < w; c++) {
            arc_set(out, ow, h - 1 - r, w - 1 - c, arc_get(grid, w, r, c));
        }
    }"""),
        ("rotate_270", _rotate_270, """
    oh = w; ow = h;
    int r, c;
    for (c = 0; c < w; c++) {
        for (r = 0; r < h; r++) {
            arc_set(out, oh, w - 1 - c, r, arc_get(grid, w, r, c));
        }
    }"""),
        ("flip_horizontal", _flip_h, """
    oh = h; ow = w;
    int r, c;
    for (r = 0; r < h; r++) {
        for (c = 0; c < w; c++) {
            arc_set(out, ow, r, w - 1 - c, arc_get(grid, w, r, c));
        }
    }"""),
        ("flip_vertical", _flip_v, """
    oh = h; ow = w;
    int r, c;
    for (r = 0; r < h; r++) {
        for (c = 0; c < w; c++) {
            arc_set(out, ow, h - 1 - r, c, arc_get(grid, w, r, c));
        }
    }"""),
        ("transpose", _transpose, """
    oh = w; ow = h;
    int r, c;
    for (r = 0; r < h; r++) {
        for (c = 0; c < w; c++) {
            arc_set(out, ow, c, r, arc_get(grid, w, r, c));
        }
    }"""),
    ]

    for name, py_fn, c_body in transforms:
        all_match = True
        for pair in pairs:
            expected = pair["output"]
            actual = py_fn(pair["input"])
            if not grids_equal(expected, actual):
                all_match = False
                break
        if all_match:
            desc = f"geometric transform: {name}"
            return Hypothesis(name, desc, _make_c_program(c_body, desc), confidence=0.95)

    return None


def _try_scale(pairs: List[dict]) -> Optional[Hypothesis]:
    """Check if output is input scaled by integer factor."""
    for scale in [2, 3]:
        all_match = True
        for pair in pairs:
            inp, out = pair["input"], pair["output"]
            h_i, w_i = _dimensions(inp)
            h_o, w_o = _dimensions(out)
            if h_o != h_i * scale or w_o != w_i * scale:
                all_match = False
                break
            for r in range(h_i):
                for c in range(w_i):
                    val = inp[r][c]
                    for dr in range(scale):
                        for dc in range(scale):
                            if out[r * scale + dr][c * scale + dc] != val:
                                all_match = False
                                break
                        if not all_match:
                            break
                    if not all_match:
                        break
                if not all_match:
                    break
            if not all_match:
                break

        if all_match:
            # Generate C for scale-up
            desc = f"scale up by {scale}x"
            body = f"""
    int scale = {scale};
    oh = 0;
    int i;
    for (i = 0; i < h; i++) oh = oh + scale;
    ow = 0;
    for (i = 0; i < w; i++) ow = ow + scale;
    int r, c, dr, dc;
    for (r = 0; r < h; r++) {{
        for (c = 0; c < w; c++) {{
            int val = arc_get(grid, w, r, c);
            for (dr = 0; dr < scale; dr++) {{
                for (dc = 0; dc < scale; dc++) {{
                    int or_ = 0;
                    for (i = 0; i < r; i++) or_ = or_ + scale;
                    or_ = or_ + dr;
                    int oc = 0;
                    for (i = 0; i < c; i++) oc = oc + scale;
                    oc = oc + dc;
                    arc_set(out, ow, or_, oc, val);
                }}
            }}
        }}
    }}"""
            return Hypothesis(f"scale_{scale}x", desc, _make_c_program(body, desc), confidence=0.9)

    return None


def _try_fill_color(pairs: List[dict]) -> Optional[Hypothesis]:
    """Check if output fills all non-zero cells with a single color,
    or fills zero cells with a color, etc."""
    # Check: all non-background cells become one color
    for pair in pairs:
        inp, out = pair["input"], pair["output"]
        if _dimensions(inp) != _dimensions(out):
            return None

    # Check: output is input with one color replaced by another
    # Find consistent single-color replacement
    replacements = {}  # (from_color, to_color) across all pairs
    for pair in pairs:
        inp, out = pair["input"], pair["output"]
        h, w = _dimensions(inp)
        for r in range(h):
            for c in range(w):
                if inp[r][c] != out[r][c]:
                    key = inp[r][c]
                    val = out[r][c]
                    if key in replacements:
                        if replacements[key] != val:
                            return None
                    else:
                        replacements[key] = val

    if not replacements or len(replacements) > 3:
        return None  # Too many replacements — probably not a simple fill

    # This is a color map! Delegate to color_map
    return None


def _try_tile_input(pairs: List[dict]) -> Optional[Hypothesis]:
    """Check if output is the input tiled NxM times."""
    for pair in pairs:
        inp, out = pair["input"], pair["output"]
        h_i, w_i = _dimensions(inp)
        h_o, w_o = _dimensions(out)
        if h_i == 0 or w_i == 0:
            return None
        if h_o % h_i != 0 or w_o % w_i != 0:
            return None

    # Check consistent tile factor
    pair0 = pairs[0]
    h_i, w_i = _dimensions(pair0["input"])
    h_o, w_o = _dimensions(pair0["output"])
    tile_r = h_o // h_i
    tile_c = w_o // w_i

    for pair in pairs:
        inp, out = pair["input"], pair["output"]
        h_i2, w_i2 = _dimensions(inp)
        h_o2, w_o2 = _dimensions(out)
        if h_o2 // h_i2 != tile_r or w_o2 // w_i2 != tile_c:
            return None  # Inconsistent tile factor
        # Verify tiling
        for r in range(h_o2):
            for c in range(w_o2):
                if out[r][c] != inp[r % h_i2][c % w_i2]:
                    return None

    desc = f"tile input {tile_r}x{tile_c}"
    body = f"""
    int tile_r = {tile_r}, tile_c = {tile_c};
    oh = 0;
    int i;
    for (i = 0; i < tile_r; i++) oh = oh + h;
    ow = 0;
    for (i = 0; i < tile_c; i++) ow = ow + w;
    int r, c;
    for (r = 0; r < oh; r++) {{
        for (c = 0; c < ow; c++) {{
            /* r % h and c % w via subtraction loop */
            int rr = r;
            while (rr >= h) rr = rr - h;
            int cc = c;
            while (cc >= w) cc = cc - w;
            arc_set(out, ow, r, c, arc_get(grid, w, rr, cc));
        }}
    }}"""
    return Hypothesis("tile_input", desc, _make_c_program(body, desc), confidence=0.9)


def _try_crop_to_nonzero(pairs: List[dict]) -> Optional[Hypothesis]:
    """Check if output is the bounding box of non-zero cells from input."""
    for pair in pairs:
        inp, out = pair["input"], pair["output"]
        h_i, w_i = _dimensions(inp)
        # Find bounding box of non-zero cells
        min_r, max_r, min_c, max_c = h_i, -1, w_i, -1
        for r in range(h_i):
            for c in range(w_i):
                if inp[r][c] != 0:
                    if r < min_r: min_r = r
                    if r > max_r: max_r = r
                    if c < min_c: min_c = c
                    if c > max_c: max_c = c

        if max_r < 0:
            return None

        cropped = [inp[r][min_c:max_c+1] for r in range(min_r, max_r+1)]
        if not grids_equal(cropped, out):
            return None

    desc = "crop to bounding box of non-zero cells"
    body = """
    /* Find bounding box of non-zero cells */
    int min_r = h, max_r = 0 - 1, min_c = w, max_c = 0 - 1;
    int r, c;
    for (r = 0; r < h; r++) {
        for (c = 0; c < w; c++) {
            int v = arc_get(grid, w, r, c);
            if (v != 0) {
                if (r < min_r) min_r = r;
                if (r > max_r) max_r = r;
                if (c < min_c) min_c = c;
                if (c > max_c) max_c = c;
            }
        }
    }
    if (max_r < 0) {
        oh = 0; ow = 0;
    } else {
        oh = max_r - min_r + 1;
        ow = max_c - min_c + 1;
        for (r = min_r; r <= max_r; r++) {
            for (c = min_c; c <= max_c; c++) {
                arc_set(out, ow, r - min_r, c - min_c, arc_get(grid, w, r, c));
            }
        }
    }"""
    return Hypothesis("crop_nonzero", desc, _make_c_program(body, desc), confidence=0.85)


def _try_gravity_down(pairs: List[dict]) -> Optional[Hypothesis]:
    """Check if non-zero cells 'fall' to the bottom of their column."""
    for pair in pairs:
        inp, out = pair["input"], pair["output"]
        h, w = _dimensions(inp)
        h_o, w_o = _dimensions(out)
        if h != h_o or w != w_o:
            return None
        # Check each column: non-zero values should be at the bottom, in order
        for c in range(w):
            col_vals = [inp[r][c] for r in range(h) if inp[r][c] != 0]
            out_col = [out[r][c] for r in range(h)]
            expected = [0] * (h - len(col_vals)) + col_vals
            if out_col != expected:
                return None

    desc = "gravity: non-zero cells fall to bottom of column"
    body = """
    oh = h; ow = w;
    arc_fill(out, h, w, 0);
    int c, r, wr;
    for (c = 0; c < w; c++) {
        /* Collect non-zero values in this column */
        int count = 0;
        for (r = 0; r < h; r++) {
            int v = arc_get(grid, w, r, c);
            if (v != 0) {
                _tmp[count] = v;
                count++;
            }
        }
        /* Place at bottom */
        wr = h - count;
        int i;
        for (i = 0; i < count; i++) {
            arc_set(out, ow, wr + i, c, _tmp[i]);
        }
    }"""
    return Hypothesis("gravity_down", desc, _make_c_program(body, desc), confidence=0.85)


# ── Main hypothesizer ────────────────────────────────────────────

# Ordered by specificity: try most specific patterns first
HYPOTHESIS_GENERATORS = [
    _try_identity,
    _try_constant_output,
    _try_color_map,
    _try_geometric_transform,
    _try_scale,
    _try_tile_input,
    _try_crop_to_nonzero,
    _try_gravity_down,
]


def generate_hypotheses(task: dict) -> List[Hypothesis]:
    """Generate candidate hypotheses for an ARC task.

    Args:
        task: dict with "train" key containing list of {"input": grid, "output": grid}

    Returns:
        List of Hypothesis objects, sorted by confidence (highest first)
    """
    pairs = task["train"]
    hypotheses = []

    for gen_fn in HYPOTHESIS_GENERATORS:
        try:
            h = gen_fn(pairs)
            if h is not None:
                hypotheses.append(h)
                logger.info(f"Hypothesis found: {h}")
        except Exception as e:
            logger.warning(f"Hypothesis generator {gen_fn.__name__} failed: {e}")

    # Sort by confidence
    hypotheses.sort(key=lambda h: h.confidence, reverse=True)
    return hypotheses


def describe_task(task: dict) -> str:
    """Generate a human-readable description of an ARC task for LLM prompting."""
    lines = []
    pairs = task["train"]
    for i, pair in enumerate(pairs):
        inp, out = pair["input"], pair["output"]
        h_i, w_i = _dimensions(inp)
        h_o, w_o = _dimensions(out)
        lines.append(f"Training pair {i}: {h_i}x{w_i} → {h_o}x{w_o}")
        lines.append(f"  Input colors: {dict(_color_histogram(inp))}")
        lines.append(f"  Output colors: {dict(_color_histogram(out))}")
    return "\n".join(lines)
