/* ARC rule: self-tile: place input copy at each non-zero cell position
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    /* Output is h*h x w*w */
    oh = 0;
    { int i;
    for (i = 0; i < h; i++) oh = oh + h; }
    ow = 0;
    { int i;
    for (i = 0; i < w; i++) ow = ow + w; }
    arc_fill(out, oh, ow, 0);
    /* For each cell in input, if non-zero, place input pattern at that tile position */
    int tr, tc, dr, dc;
    for (tr = 0; tr < h; tr++) {
        for (tc = 0; tc < w; tc++) {
            if (arc_get(grid, w, tr, tc) != 0) {
                for (dr = 0; dr < h; dr++) {
                    for (dc = 0; dc < w; dc++) {
                        int or_ = 0;
                        int i;
                        for (i = 0; i < tr; i++) or_ = or_ + h;
                        or_ = or_ + dr;
                        int oc = 0;
                        for (i = 0; i < tc; i++) oc = oc + w;
                        oc = oc + dc;
                        arc_set(out, ow, or_, oc, arc_get(grid, w, dr, dc));
                    }
                }
            }
        }
    }
    arc_emit_grid(out, oh, ow);
}
