/* ARC rule: fill enclosed regions with color 4
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    oh = h; ow = w;
    /* Copy input to output */
    { int total = 0, ii;
    for (ii = 0; ii < h; ii++) total = total + w;
    for (ii = 0; ii < total; ii++) out[ii] = grid[ii]; }
    /* BFS from border: mark reachable bg cells as -1 in out */
    int bg = 0;
    int fill = 4;
    int qhead = 0, qtail = 0;
    int r, c;
    /* Seed border bg cells */
    for (r = 0; r < h; r++) {
        for (c = 0; c < w; c++) {
            if ((r == 0 || r == h - 1 || c == 0 || c == w - 1) &&
                arc_get(out, w, r, c) == bg) {
                arc_set(out, w, r, c, 0 - 1);
                _qr[qtail] = r;
                _qc[qtail] = c;
                qtail++;
            }
        }
    }
    /* BFS */
    while (qhead < qtail) {
        int pr = _qr[qhead];
        int pc = _qc[qhead];
        qhead++;
        /* 4 neighbors: up, down, left, right */
        int di;
        for (di = 0; di < 4; di++) {
            int nr = pr;
            int nc = pc;
            if (di == 0) nr = pr - 1;
            if (di == 1) nr = pr + 1;
            if (di == 2) nc = pc - 1;
            if (di == 3) nc = pc + 1;
            if (nr >= 0 && nr < h && nc >= 0 && nc < w) {
                if (arc_get(out, w, nr, nc) == bg) {
                    arc_set(out, w, nr, nc, 0 - 1);
                    _qr[qtail] = nr;
                    _qc[qtail] = nc;
                    qtail++;
                }
            }
        }
    }
    /* Fill remaining bg cells with fill_color, restore -1 to bg */
    { int total = 0, ii;
    for (ii = 0; ii < h; ii++) total = total + w;
    for (ii = 0; ii < total; ii++) {
        if (out[ii] == bg) out[ii] = fill;
        if (out[ii] == (0 - 1)) out[ii] = bg;
    } }
    arc_emit_grid(out, oh, ow);
}
