/* ARC rule: split at col 3, and halves, fill with 2
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    /* Split at column separator */
    int sep_col = 3;
    int out_w = sep_col;
    oh = h; ow = out_w;
    arc_fill(out, h, out_w, 0);
    int r, c;
    for (r = 0; r < h; r++) {
        for (c = 0; c < out_w; c++) {
            int left_val = arc_get(grid, w, r, c);
            int right_val = arc_get(grid, w, r, sep_col + 1 + c);
            int flag = 0;
            if (left_val != 0 && right_val != 0) flag = 1;
            if (flag) arc_set(out, ow, r, c, 2);
        }
    }
    arc_emit_grid(out, oh, ow);
}
