/* ARC rule: rank bars
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    oh = h; ow = w;
    arc_fill(out, h, w, 0);
    /* Find height of each bar (column of 5s from bottom) */
    int heights[30];
    int cols[30];
    int nbars = 0;
    int c, r;
    for (c = 0; c < w; c++) {
        int height = 0;
        for (r = 0; r < h; r++) {
            if (arc_get(grid, w, r, c) == 5) height++;
        }
        if (height > 0) {
            heights[nbars] = height;
            cols[nbars] = c;
            nbars++;
        }
    }
    /* Sort by height descending (bubble sort) */
    int i, j;
    for (i = 0; i < nbars; i++) {
        for (j = i + 1; j < nbars; j++) {
            if (heights[j] > heights[i]) {
                int tmp = heights[i]; heights[i] = heights[j]; heights[j] = tmp;
                tmp = cols[i]; cols[i] = cols[j]; cols[j] = tmp;
            }
        }
    }
    /* Assign colors: tallest=1, next=2, etc */
    for (i = 0; i < nbars; i++) {
        int color = i + 1;
        int col = cols[i];
        /* Fill from bottom up for height cells */
        for (r = h - heights[i]; r < h; r++) {
            arc_set(out, w, r, col, color);
        }
    }
    arc_emit_grid(out, oh, ow);
}
