/* ARC rule: color neighbor patterns
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    oh = h; ow = w;
    { int total = 0, ii;
    for (ii = 0; ii < h; ii++) total = total + w;
    for (ii = 0; ii < total; ii++) out[ii] = grid[ii]; }
    int r, c;
    for (r = 0; r < h; r++) {
        for (c = 0; c < w; c++) {
            int v = arc_get(grid, w, r, c);
            if (v == 2) {
                /* Diagonal neighbors get 4 */
                if (r > 0 && c > 0 && arc_get(out, w, r-1, c-1) == 0) arc_set(out, w, r-1, c-1, 4);
                if (r > 0 && c < w-1 && arc_get(out, w, r-1, c+1) == 0) arc_set(out, w, r-1, c+1, 4);
                if (r < h-1 && c > 0 && arc_get(out, w, r+1, c-1) == 0) arc_set(out, w, r+1, c-1, 4);
                if (r < h-1 && c < w-1 && arc_get(out, w, r+1, c+1) == 0) arc_set(out, w, r+1, c+1, 4);
            }
            if (v == 1) {
                /* Orthogonal neighbors get 7 */
                if (r > 0 && arc_get(out, w, r-1, c) == 0) arc_set(out, w, r-1, c, 7);
                if (r < h-1 && arc_get(out, w, r+1, c) == 0) arc_set(out, w, r+1, c, 7);
                if (c > 0 && arc_get(out, w, r, c-1) == 0) arc_set(out, w, r, c-1, 7);
                if (c < w-1 && arc_get(out, w, r, c+1) == 0) arc_set(out, w, r, c+1, 7);
            }
        }
    }
    arc_emit_grid(out, oh, ow);
}
