/* ARC rule: line by color v2
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    oh = h; ow = w;
    arc_fill(out, h, w, 0);
    int r, c;
    /* First pass: vertical lines (color 2) */
    for (r = 0; r < h; r++) {
        for (c = 0; c < w; c++) {
            if (arc_get(grid, w, r, c) == 2) {
                int rr;
                for (rr = 0; rr < h; rr++) arc_set(out, w, rr, c, 2);
            }
        }
    }
    /* Second pass: horizontal lines (color 1, 3) overwrite */
    for (r = 0; r < h; r++) {
        for (c = 0; c < w; c++) {
            int v = arc_get(grid, w, r, c);
            if (v == 1 || v == 3) {
                int cc;
                for (cc = 0; cc < w; cc++) arc_set(out, w, r, cc, v);
            }
        }
    }
    arc_emit_grid(out, oh, ow);
}
