/* ARC rule: crop to bounding box of non-zero cells
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    /* Find bounding box of non-zero cells */
    int min_r = h, max_r = 0 - 1, min_c = w, max_c = 0 - 1;
    int r, c;
    for (r = 0; r < h; r++) {
        for (c = 0; c < w; c++) {
            int v = arc_get(grid, w, r, c);
            if (v != 0) {
                if (r < min_r) min_r = r;
                if (r > max_r) max_r = r;
                if (c < min_c) min_c = c;
                if (c > max_c) max_c = c;
            }
        }
    }
    if (max_r < 0) {
        oh = 0; ow = 0;
    } else {
        oh = max_r - min_r + 1;
        ow = max_c - min_c + 1;
        for (r = min_r; r <= max_r; r++) {
            for (c = min_c; c <= max_c; c++) {
                arc_set(out, ow, r - min_r, c - min_c, arc_get(grid, w, r, c));
            }
        }
    }
    arc_emit_grid(out, oh, ow);
}
