/* ARC rule: gravity: non-zero cells fall to bottom of column
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    oh = h; ow = w;
    arc_fill(out, h, w, 0);
    int c, r, wr;
    for (c = 0; c < w; c++) {
        /* Collect non-zero values in this column */
        int count = 0;
        for (r = 0; r < h; r++) {
            int v = arc_get(grid, w, r, c);
            if (v != 0) {
                _tmp[count] = v;
                count++;
            }
        }
        /* Place at bottom */
        wr = h - count;
        int i;
        for (i = 0; i < count; i++) {
            arc_set(out, ow, wr + i, c, _tmp[i]);
        }
    }
    arc_emit_grid(out, oh, ow);
}
