/* ARC rule: connect same-color cells with H/V lines (color=3)
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    oh = h; ow = w;
    { int total = 0, ii;
    for (ii = 0; ii < h; ii++) total = total + w;
    for (ii = 0; ii < total; ii++) out[ii] = grid[ii]; }
    /* For each color, connect cells on same row/col */
    int color;
    for (color = 1; color < 10; color++) {
        /* Find all cells of this color */
        int cells_r[100], cells_c[100], ncells = 0;
        int r, c;
        for (r = 0; r < h; r++) {
            for (c = 0; c < w; c++) {
                if (arc_get(grid, w, r, c) == color && ncells < 100) {
                    cells_r[ncells] = r;
                    cells_c[ncells] = c;
                    ncells++;
                }
            }
        }
        if (ncells < 2) continue;
        int line_color = 3;
        /* Draw H/V lines between pairs */
        int i, j;
        for (i = 0; i < ncells; i++) {
            for (j = i + 1; j < ncells; j++) {
                int r1 = cells_r[i], c1 = cells_c[i];
                int r2 = cells_r[j], c2 = cells_c[j];
                if (r1 == r2) {
                    int lo = c1, hi = c2;
                    if (c2 < c1) { lo = c2; hi = c1; }
                    int cc;
                    for (cc = lo + 1; cc < hi; cc++) {
                        if (arc_get(out, w, r1, cc) == 0)
                            arc_set(out, w, r1, cc, line_color);
                    }
                }
                if (c1 == c2) {
                    int lo = r1, hi = r2;
                    if (r2 < r1) { lo = r2; hi = r1; }
                    int rr;
                    for (rr = lo + 1; rr < hi; rr++) {
                        if (arc_get(out, w, rr, c1) == 0)
                            arc_set(out, w, rr, c1, line_color);
                    }
                }
            }
        }
    }
    arc_emit_grid(out, oh, ow);
}
