/* ARC rule: split at row 6, xor halves, fill with 3
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    int sep_row = 6;
    int out_h = sep_row;
    oh = out_h; ow = w;
    arc_fill(out, out_h, w, 0);
    int r, c;
    for (r = 0; r < out_h; r++) {
        for (c = 0; c < w; c++) {
            int top_val = arc_get(grid, w, r, c);
            int bot_val = arc_get(grid, w, sep_row + 1 + r, c);
            int flag = 0;
            if ((top_val != 0) != (bot_val != 0)) flag = 1;
            if (flag) arc_set(out, ow, r, c, 3);
        }
    }
    arc_emit_grid(out, oh, ow);
}
