/* ARC rule: geometric transform: flip_horizontal
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    oh = h; ow = w;
    int r, c;
    for (r = 0; r < h; r++) {
        for (c = 0; c < w; c++) {
            arc_set(out, ow, r, w - 1 - c, arc_get(grid, w, r, c));
        }
    }
    arc_emit_grid(out, oh, ow);
}
