/* ARC rule: tile input 1x2
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    int tile_r = 1, tile_c = 2;
    oh = 0;
    int i;
    for (i = 0; i < tile_r; i++) oh = oh + h;
    ow = 0;
    for (i = 0; i < tile_c; i++) ow = ow + w;
    int r, c;
    for (r = 0; r < oh; r++) {
        for (c = 0; c < ow; c++) {
            /* r % h and c % w via subtraction loop */
            int rr = r;
            while (rr >= h) rr = rr - h;
            int cc = c;
            while (cc >= w) cc = cc - w;
            arc_set(out, ow, r, c, arc_get(grid, w, rr, cc));
        }
    }
    arc_emit_grid(out, oh, ow);
}
