/* ARC rule: bg cells with 2 4-neighbors of color 1 become 2
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    oh = h; ow = w;
    { int total = 0, ii;
    for (ii = 0; ii < h; ii++) total = total + w;
    for (ii = 0; ii < total; ii++) out[ii] = grid[ii]; }
    int r, c;
    for (r = 0; r < h; r++) {
        for (c = 0; c < w; c++) {
            if (arc_get(grid, w, r, c) == 0) {
                
            int nn = 0;
            if (r > 0 && arc_get(grid, w, r - 1, c) == 1) nn++;
            if (r < h - 1 && arc_get(grid, w, r + 1, c) == 1) nn++;
            if (c > 0 && arc_get(grid, w, r, c - 1) == 1) nn++;
            if (c < w - 1 && arc_get(grid, w, r, c + 1) == 1) nn++;
                if (nn == 2) arc_set(out, w, r, c, 2);
            }
        }
    }
    arc_emit_grid(out, oh, ow);
}
