/* ARC rule: scale up by 2x
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    int scale = 2;
    oh = 0;
    int i;
    for (i = 0; i < h; i++) oh = oh + scale;
    ow = 0;
    for (i = 0; i < w; i++) ow = ow + scale;
    int r, c, dr, dc;
    for (r = 0; r < h; r++) {
        for (c = 0; c < w; c++) {
            int val = arc_get(grid, w, r, c);
            for (dr = 0; dr < scale; dr++) {
                for (dc = 0; dc < scale; dc++) {
                    int or_ = 0;
                    for (i = 0; i < r; i++) or_ = or_ + scale;
                    or_ = or_ + dr;
                    int oc = 0;
                    for (i = 0; i < c; i++) oc = oc + scale;
                    oc = oc + dc;
                    arc_set(out, ow, or_, oc, val);
                }
            }
        }
    }
    arc_emit_grid(out, oh, ow);
}
