/* ARC rule: color map: 1->1, 2->2, 3->3, 4->4, 5->8, 6->6, 7->7, 8->5, 9->9
 * Auto-generated by self-compiling intelligence loop.
 */
#include "arc/arc_grid.h"

/* Static arrays to avoid WASM stack overflow (4KB stack limit) */
static int _grid[900];
static int _out[900];
static int _tmp[32];
static int _qr[900];  /* BFS queue: row indices */
static int _qc[900];  /* BFS queue: col indices */
static int _h_arr[1];
static int _w_arr[1];

void compute(const char *input) {
    int *grid = _grid;
    int *out = _out;
    arc_parse_grid(input, grid, _h_arr, _w_arr);
    int h = _h_arr[0], w = _w_arr[0];
    int oh, ow;

    /* Color mapping lookup table */
    int lut[10];
    lut[0]=0; lut[1]=1; lut[2]=2; lut[3]=3; lut[4]=4;
    lut[5]=8; lut[6]=6; lut[7]=7; lut[8]=5; lut[9]=9;
    oh = h; ow = w;
    int total = 0;
    int i;
    for (i = 0; i < h; i++) total = total + w;
    for (i = 0; i < total; i++) {
        out[i] = lut[grid[i]];
    }
    arc_emit_grid(out, oh, ow);
}
